services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./flaskr/data:/Moadata/flaskr/data
    expose:
      - 5000

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./flaskr/templates:/staticfiles